//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.FrameWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PPC_RentalEntities : DbContext
    {
        public PPC_RentalEntities()
            : base("name=PPC_RentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<DISCTRICT_TABLE> DISCTRICT_TABLE { get; set; }
        public virtual DbSet<FEATURE_TABLE> FEATURE_TABLE { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<PROJECT_FEATURE_TABLE> PROJECT_FEATURE_TABLE { get; set; }
        public virtual DbSet<PROJECT_STATUS_TABLE> PROJECT_STATUS_TABLE { get; set; }
        public virtual DbSet<PROJECT_TABLE> PROJECT_TABLE { get; set; }
        public virtual DbSet<PROJECT_TYPE_TABLE> PROJECT_TYPE_TABLE { get; set; }
        public virtual DbSet<STREET_TABLE> STREET_TABLE { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<USER_TABLE> USER_TABLE { get; set; }
        public virtual DbSet<WARD_TABLE> WARD_TABLE { get; set; }
    }
}
