//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.FrameWork
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class PROJECT_TYPE_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJECT_TYPE_TABLE()
        {
            this.PROJECT_TABLE = new HashSet<PROJECT_TABLE>();
        }
    
        public int id { get; set; }
        // Doi ten hien thi tren trinh duyet
        [DisplayName("Loại Project")]
        // Truong yeu cau bat buoc nhap
        [Required(ErrorMessage ="Bạn chưa nhập loại Project")]
        [StringLength(50,ErrorMessage="Số kí tự tối đa là 50")]
        public string TypeName { get; set; }

        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_TABLE> PROJECT_TABLE { get; set; }
    }
}
