//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.FrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_FEATURE_TABLE
    {
        public int id { get; set; }
        public int Project_ID { get; set; }
        public int Feature_ID { get; set; }
    
        public virtual FEATURE_TABLE FEATURE_TABLE { get; set; }
        public virtual PROJECT_TABLE PROJECT_TABLE { get; set; }
    }
}
