//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.FrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECT_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJECT_TABLE()
        {
            this.PROJECT_FEATURE_TABLE = new HashSet<PROJECT_FEATURE_TABLE>();
        }
    
        public int id { get; set; }
        public string Avatar { get; set; }
        public string Images { get; set; }
        public int ProjectType_ID { get; set; }
        public string ProjectName { get; set; }
        public string Content { get; set; }
        public string City { get; set; }
        public int District_ID { get; set; }
        public int Ward_ID { get; set; }
        public int Street_ID { get; set; }
        public int Price { get; set; }
        public string UnitPrice { get; set; }
        public string Area { get; set; }
        public int BedRoom { get; set; }
        public int BathRoom { get; set; }
        public int PackingPlace { get; set; }
        public int User_ID { get; set; }
        public System.DateTime Created_at { get; set; }
        public int Status_ID { get; set; }
        public string Note { get; set; }
        public System.DateTime Updated_at { get; set; }
        public int Sale_ID { get; set; }
    
        public virtual DISCTRICT_TABLE DISCTRICT_TABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT_FEATURE_TABLE> PROJECT_FEATURE_TABLE { get; set; }
        public virtual PROJECT_STATUS_TABLE PROJECT_STATUS_TABLE { get; set; }
        public virtual PROJECT_TYPE_TABLE PROJECT_TYPE_TABLE { get; set; }
        public virtual STREET_TABLE STREET_TABLE { get; set; }
        public virtual USER_TABLE USER_TABLE { get; set; }
        public virtual WARD_TABLE WARD_TABLE { get; set; }
    }
}
